name: Code Quality
on:
  push:
    branches:
      - main
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            target
      - run: rustup component add clippy rustfmt
      - run: cargo fmt -- --check
      - run: cargo clippy -- --deny clippy::pedantic
      - run: cargo test --verbose
