name: Code Quality
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  format:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            target
      - run: cargo clippy -- --deny warnings
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            target
      - run: cargo build
