name: "Claim daily reward"
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
jobs:
  claim_daily_reward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - env:
          COOKIES: ${{ secrets.COOKIES }}
          GAMES: ${{ vars.GAMES }}
        run: uv run kirara.py
