name: "Claim daily reward"
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
jobs:
  claim_daily_reward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - env:
          COOKIES: ${{ secrets.COOKIES }}
          GENSHIN: ${{ vars.GENSHIN }}
          HONKAI: ${{ vars.HONKAI }}
          STARRAIL: ${{ vars.STARRAIL }}
          ZZZ: ${{ vars.ZZZ }}
        run: python kirara.py
