name: "Claim daily reward"
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
jobs:
  claim_daily_reward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - env:
          COOKIES: ${{ secrets.COOKIES }}
          GENSHIN_DAILY: ${{ vars.GENSHIN_DAILY }}
          HONKAI_DAILY: ${{ vars.HONKAI_DAILY }}
          STARRAIL_DAILY: ${{ vars.STARRAIL_DAILY }}
          ZZZ_DAILY: ${{ vars.ZZZ_DAILY }}
        run: python kirara.py
